-- Generated by scripts/build-contact-book-migration.mjs.

-- Do not include seed.sql: production class data is imported separately.

begin;

-- 共用英文單字系統的 Auth 相容設定
-- Source: supabase/shared-project-compatibility.sql
-- 英文單字測驗與線上聯絡簿共用同一個 Supabase 專案。
-- 英文單字系統原有的 auth.users 觸發器只應建立單字系統 profile，
-- 僅標記為 vocab 的共用帳號會建立英文 profiles；
-- 聯絡簿角色與核准狀態另由 public.contact_book_profiles 管理。
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(new.raw_user_meta_data->>'app_scope', 'vocab') <> 'vocab' then
    return new;
  end if;

  insert into public.profiles (id, username, role, level_book, level_lesson)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    'student',
    'B1',
    'L1'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

-- 線上聯絡簿資料庫結構
-- Source: supabase/schema.sql
-- 線上聯絡簿：Supabase 初步資料模型
-- 狀態：設計草案，尚未在任何 Supabase 專案執行。

create extension if not exists pgcrypto;
create extension if not exists citext;
create extension if not exists btree_gist;

create table if not exists public.schools (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.academic_years (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools(id) on delete cascade,
  school_year integer not null check (school_year > 0),
  starts_on date not null,
  ends_on date not null,
  created_at timestamptz not null default now(),
  constraint academic_year_dates_valid check (ends_on >= starts_on),
  constraint academic_year_school_unique unique (school_id, school_year)
);

create table if not exists public.academic_terms (
  id uuid primary key default gen_random_uuid(),
  academic_year_id uuid not null references public.academic_years(id) on delete cascade,
  semester smallint not null check (semester in (1, 2)),
  starts_on date not null,
  ends_on date not null,
  created_at timestamptz not null default now(),
  constraint academic_term_dates_valid check (ends_on >= starts_on),
  constraint academic_term_year_unique unique (academic_year_id, semester)
);

create table if not exists public.classes (
  id uuid primary key default gen_random_uuid(),
  academic_year_id uuid not null references public.academic_years(id) on delete cascade,
  grade_level smallint not null check (grade_level between 1 and 12),
  class_number smallint not null check (class_number > 0),
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint class_year_name_unique unique (academic_year_id, name)
);

create table if not exists public.contact_book_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username citext not null unique,
  display_name text not null,
  user_type text not null check (user_type in ('admin', 'teacher', 'student')),
  approval_status text not null default 'pending'
    check (approval_status in ('pending', 'approved', 'rejected', 'suspended')),
  is_active boolean not null default true,
  approved_by uuid references public.contact_book_profiles(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  profile_id uuid unique references public.contact_book_profiles(id) on delete set null,
  student_id_code citext not null unique,
  seat_number smallint not null check (seat_number > 0),
  full_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint student_class_seat_unique unique (class_id, seat_number)
);

create table if not exists public.student_activation_codes (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create unique index if not exists one_unused_activation_code_per_student
  on public.student_activation_codes(student_id)
  where used_at is null;

-- 公開登入端點的節流狀態。只保存雜湊後的請求識別，不保存原始 IP 或帳號。
create table if not exists public.auth_rate_limits (
  key_hash text not null,
  action text not null,
  window_started_at timestamptz not null default now(),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  blocked_until timestamptz,
  updated_at timestamptz not null default now(),
  primary key (key_hash, action)
);

create table if not exists public.subjects (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools(id) on delete cascade,
  code citext not null,
  name text not null,
  created_at timestamptz not null default now(),
  constraint subject_school_code_unique unique (school_id, code),
  constraint subject_school_name_unique unique (school_id, name)
);

create table if not exists public.class_subjects (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  subject_id uuid not null references public.subjects(id) on delete restrict,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint class_subject_unique unique (class_id, subject_id)
);

create table if not exists public.class_staff_assignments (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  profile_id uuid not null references public.contact_book_profiles(id) on delete cascade,
  role text not null check (role in ('homeroom_teacher', 'subject_teacher')),
  class_subject_id uuid references public.class_subjects(id) on delete cascade,
  starts_on date not null,
  ends_on date,
  created_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint staff_assignment_dates_valid check (ends_on is null or ends_on >= starts_on),
  constraint staff_subject_role_valid check (
    (role = 'homeroom_teacher' and class_subject_id is null)
    or (role = 'subject_teacher' and class_subject_id is not null)
  )
);

create unique index if not exists active_staff_assignment_unique
  on public.class_staff_assignments(class_id, profile_id, role, coalesce(class_subject_id, '00000000-0000-0000-0000-000000000000'::uuid))
  where ends_on is null;

create table if not exists public.student_helper_assignments (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  class_subject_id uuid not null references public.class_subjects(id) on delete cascade,
  helper_role text not null check (helper_role in ('homework_leader', 'subject_helper')),
  starts_on date not null,
  ends_on date,
  created_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint helper_assignment_dates_valid check (ends_on is null or ends_on >= starts_on)
);

create unique index if not exists active_helper_assignment_unique
  on public.student_helper_assignments(student_id, class_subject_id, helper_role)
  where ends_on is null;

create table if not exists public.student_subject_groups (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  class_subject_id uuid not null references public.class_subjects(id) on delete cascade,
  academic_term_id uuid not null references public.academic_terms(id) on delete cascade,
  group_code citext not null check (length(trim(group_code::text)) > 0),
  effective_from date not null,
  effective_to date,
  created_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint student_group_dates_valid check (effective_to is null or effective_to >= effective_from),
  constraint student_group_period_no_overlap exclude using gist (
    student_id with =,
    class_subject_id with =,
    daterange(effective_from, coalesce(effective_to, 'infinity'::date), '[]') with &&
  )
);

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  class_subject_id uuid not null references public.class_subjects(id) on delete cascade,
  academic_term_id uuid not null references public.academic_terms(id) on delete restrict,
  assignment_date date not null,
  content text not null check (length(trim(content)) > 0),
  due_at timestamptz not null,
  target_type text not null check (target_type in ('common', 'group')),
  target_group_code citext,
  published_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  published_by_display_name text not null,
  published_at timestamptz not null default now(),
  is_active boolean not null default true,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assignment_target_valid check (
    (target_type = 'common' and target_group_code is null)
    or (target_type = 'group' and target_group_code is not null)
  )
);

create index if not exists assignments_subject_due_idx
  on public.assignments(class_subject_id, due_at desc);

create table if not exists public.assignment_recipients (
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  audience_source text not null check (audience_source in ('common', 'group_snapshot', 'manual_adjustment')),
  group_code_snapshot citext,
  created_at timestamptz not null default now(),
  primary key (assignment_id, student_id)
);

create index if not exists assignment_recipients_student_idx
  on public.assignment_recipients(student_id, assignment_id);

create table if not exists public.submission_checks (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  check_stage text not null check (check_stage in ('helper', 'teacher')),
  result text not null check (result in ('all_submitted', 'exceptions_recorded')),
  checked_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  checked_at timestamptz not null default now(),
  note text,
  constraint submission_check_assignment_stage_unique unique (assignment_id, check_stage)
);

create table if not exists public.submission_exceptions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  initial_reason text not null
    check (initial_reason in ('incomplete', 'not_brought', 'late', 'leave', 'official_leave', 'exempt')),
  current_reason text not null
    check (current_reason in ('incomplete', 'not_brought', 'late', 'leave', 'official_leave', 'exempt')),
  workflow_state text not null default 'open'
    check (workflow_state in ('open', 'made_up', 'waived')),
  follow_up_due_at timestamptz,
  counts_as_missing boolean not null default false,
  counts_as_late boolean not null default false,
  resolved_at timestamptz,
  hide_after timestamptz,
  first_recorded_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  last_updated_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint submission_exception_assignment_student_unique unique (assignment_id, student_id),
  constraint absence_follow_up_required check (
    current_reason not in ('leave', 'official_leave') or follow_up_due_at is not null
  ),
  constraint resolved_dates_valid check (
    (workflow_state = 'open' and resolved_at is null and hide_after is null)
    or (workflow_state in ('made_up', 'waived') and resolved_at is not null and hide_after is not null)
  )
);

create index if not exists submission_exceptions_student_idx
  on public.submission_exceptions(student_id, created_at desc);

create index if not exists submission_exceptions_active_idx
  on public.submission_exceptions(workflow_state, hide_after);

create table if not exists public.submission_status_events (
  id uuid primary key default gen_random_uuid(),
  submission_exception_id uuid not null references public.submission_exceptions(id) on delete cascade,
  from_reason text,
  to_reason text not null,
  from_state text,
  to_state text not null,
  counts_as_missing boolean not null,
  counts_as_late boolean not null,
  changed_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists submission_events_exception_idx
  on public.submission_status_events(submission_exception_id, created_at);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  scope text not null check (scope in ('school', 'class')),
  title text not null check (length(trim(title)) > 0),
  content text,
  image_path text,
  image_alt_text text,
  published_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  published_at timestamptz not null default now(),
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists announcements_class_published_idx
  on public.announcements(class_id, published_at desc);

create table if not exists public.announcement_reads (
  announcement_id uuid not null references public.announcements(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (announcement_id, student_id)
);

create table if not exists public.honor_entries (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  student_display_name text not null,
  title text not null check (length(trim(title)) > 0),
  description text,
  awarded_on date not null,
  created_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists honor_entries_class_date_idx
  on public.honor_entries(class_id, awarded_on desc);

-- 成績模組僅預留資料結構，第一版不建立正式操作畫面。
create table if not exists public.assessment_periods (
  id uuid primary key default gen_random_uuid(),
  academic_term_id uuid not null references public.academic_terms(id) on delete cascade,
  name text not null,
  starts_on date,
  ends_on date,
  sort_order integer not null default 0,
  constraint assessment_period_term_name_unique unique (academic_term_id, name)
);

create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  class_subject_id uuid not null references public.class_subjects(id) on delete cascade,
  assessment_period_id uuid not null references public.assessment_periods(id) on delete cascade,
  name text not null,
  maximum_score numeric(7, 2) not null default 100 check (maximum_score > 0),
  assessed_on date,
  created_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.student_scores (
  id uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  score numeric(7, 2) not null check (score >= 0),
  recorded_by uuid not null references public.contact_book_profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint student_assessment_score_unique unique (assessment_id, student_id)
);

-- 由 Edge Function 使用 service_role 呼叫，將學生啟用相關資料以單一交易完成。
create or replace function public.complete_student_activation(
  p_student_id_code text,
  p_code_hash text,
  p_profile_id uuid,
  p_username text
)
returns table (student_id uuid, display_name text)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_student public.students%rowtype;
  target_code public.student_activation_codes%rowtype;
begin
  select * into target_student
  from public.students s
  where s.student_id_code = p_student_id_code
    and s.is_active
  for update;

  if not found or target_student.profile_id is not null then
    raise exception 'invalid_activation';
  end if;

  select * into target_code
  from public.student_activation_codes sac
  where sac.student_id = target_student.id
    and sac.used_at is null
    and sac.expires_at > now()
  for update;

  if not found or target_code.code_hash <> p_code_hash then
    raise exception 'invalid_activation';
  end if;

  insert into public.contact_book_profiles (
    id,
    username,
    display_name,
    user_type,
    approval_status,
    approved_at
  ) values (
    p_profile_id,
    p_username,
    target_student.full_name,
    'student',
    'approved',
    now()
  );

  update public.students
  set profile_id = p_profile_id,
      updated_at = now()
  where id = target_student.id;

  update public.student_activation_codes
  set used_at = now()
  where id = target_code.id;

  return query select target_student.id, target_student.full_name;
end;
$$;

-- 教師自行註冊後只建立 pending profile，導師核准後才給班級與科目權限。
create or replace function public.register_pending_teacher(
  p_profile_id uuid,
  p_username text,
  p_display_name text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.contact_book_profiles (
    id,
    username,
    display_name,
    user_type,
    approval_status
  ) values (
    p_profile_id,
    p_username,
    p_display_name,
    'teacher',
    'pending'
  );
end;
$$;

create or replace function public.consume_auth_rate_limit(
  p_key_hash text,
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_record public.auth_rate_limits%rowtype;
  window_interval interval;
begin
  if p_limit < 1 or p_window_seconds < 1 then
    raise exception 'invalid_rate_limit_config';
  end if;

  window_interval := make_interval(secs => p_window_seconds);

  insert into public.auth_rate_limits (key_hash, action, attempt_count)
  values (p_key_hash, p_action, 0)
  on conflict (key_hash, action) do nothing;

  select * into current_record
  from public.auth_rate_limits arl
  where arl.key_hash = p_key_hash and arl.action = p_action
  for update;

  if current_record.blocked_until is not null and current_record.blocked_until > now() then
    return false;
  end if;

  if current_record.window_started_at + window_interval <= now() then
    update public.auth_rate_limits
    set window_started_at = now(),
        attempt_count = 1,
        blocked_until = null,
        updated_at = now()
    where key_hash = p_key_hash and action = p_action;
    return true;
  end if;

  if current_record.attempt_count >= p_limit then
    update public.auth_rate_limits
    set blocked_until = current_record.window_started_at + window_interval,
        updated_at = now()
    where key_hash = p_key_hash and action = p_action;
    return false;
  end if;

  update public.auth_rate_limits
  set attempt_count = attempt_count + 1,
      updated_at = now()
  where key_hash = p_key_hash and action = p_action;
  return true;
end;
$$;

revoke all on function public.complete_student_activation(text, text, uuid, text)
  from public, anon, authenticated;
grant execute on function public.complete_student_activation(text, text, uuid, text)
  to service_role;

revoke all on function public.register_pending_teacher(uuid, text, text)
  from public, anon, authenticated;
grant execute on function public.register_pending_teacher(uuid, text, text)
  to service_role;

revoke all on function public.consume_auth_rate_limit(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_auth_rate_limit(text, text, integer, integer)
  to service_role;

create or replace function public.contact_book_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.prepare_submission_exception()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if new.initial_reason in ('incomplete', 'not_brought') then
      new.counts_as_missing = true;
    elsif new.initial_reason = 'late' then
      new.counts_as_late = true;
    end if;
  end if;

  if new.workflow_state in ('made_up', 'waived') then
    new.resolved_at = coalesce(new.resolved_at, now());
    new.hide_after = coalesce(new.hide_after, new.resolved_at + interval '3 days');
  else
    new.resolved_at = null;
    new.hide_after = null;
  end if;

  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.log_submission_status_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.submission_status_events (
      submission_exception_id,
      from_reason,
      to_reason,
      from_state,
      to_state,
      counts_as_missing,
      counts_as_late,
      changed_by
    ) values (
      new.id,
      null,
      new.current_reason,
      null,
      new.workflow_state,
      new.counts_as_missing,
      new.counts_as_late,
      new.first_recorded_by
    );
  elsif old.current_reason is distinct from new.current_reason
     or old.workflow_state is distinct from new.workflow_state
     or old.counts_as_missing is distinct from new.counts_as_missing
     or old.counts_as_late is distinct from new.counts_as_late then
    insert into public.submission_status_events (
      submission_exception_id,
      from_reason,
      to_reason,
      from_state,
      to_state,
      counts_as_missing,
      counts_as_late,
      changed_by
    ) values (
      new.id,
      old.current_reason,
      new.current_reason,
      old.workflow_state,
      new.workflow_state,
      new.counts_as_missing,
      new.counts_as_late,
      new.last_updated_by
    );
  end if;

  return new;
end;
$$;

drop trigger if exists classes_set_updated_at on public.classes;
create trigger classes_set_updated_at
before update on public.classes
for each row execute function public.contact_book_set_updated_at();

drop trigger if exists profiles_set_updated_at on public.contact_book_profiles;
create trigger profiles_set_updated_at
before update on public.contact_book_profiles
for each row execute function public.contact_book_set_updated_at();

drop trigger if exists students_set_updated_at on public.students;
create trigger students_set_updated_at
before update on public.students
for each row execute function public.contact_book_set_updated_at();

drop trigger if exists assignments_set_updated_at on public.assignments;
create trigger assignments_set_updated_at
before update on public.assignments
for each row execute function public.contact_book_set_updated_at();

drop trigger if exists submission_exceptions_prepare on public.submission_exceptions;
create trigger submission_exceptions_prepare
before insert or update on public.submission_exceptions
for each row execute function public.prepare_submission_exception();

drop trigger if exists submission_exceptions_log_event on public.submission_exceptions;
create trigger submission_exceptions_log_event
after insert or update on public.submission_exceptions
for each row execute function public.log_submission_status_event();

drop trigger if exists announcements_set_updated_at on public.announcements;
create trigger announcements_set_updated_at
before update on public.announcements
for each row execute function public.contact_book_set_updated_at();

drop trigger if exists honor_entries_set_updated_at on public.honor_entries;
create trigger honor_entries_set_updated_at
before update on public.honor_entries
for each row execute function public.contact_book_set_updated_at();

drop trigger if exists student_scores_set_updated_at on public.student_scores;
create trigger student_scores_set_updated_at
before update on public.student_scores
for each row execute function public.contact_book_set_updated_at();

-- 線上聯絡簿資料存取政策
-- Source: supabase/rls-policies.sql
-- 線上聯絡簿：RLS 權限草案
-- 必須在 schema.sql 之後執行。正式執行前仍需以各角色測試帳號驗證。

create or replace function public.is_approved_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.contact_book_profiles p
    where p.id = auth.uid()
      and p.approval_status = 'approved'
      and p.is_active
  );
$$;

create or replace function public.contact_book_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.contact_book_profiles p
    where p.id = auth.uid()
      and p.user_type = 'admin'
      and p.approval_status = 'approved'
      and p.is_active
  );
$$;

create or replace function public.is_student_self(target_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.students s
    join public.contact_book_profiles p on p.id = s.profile_id
    where s.id = target_student_id
      and s.profile_id = auth.uid()
      and s.is_active
      and p.approval_status = 'approved'
      and p.is_active
  );
$$;

create or replace function public.current_student_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select s.id
  from public.students s
  where s.profile_id = auth.uid() and s.is_active
  limit 1;
$$;

create or replace function public.can_manage_class(target_class_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.contact_book_is_admin() or exists (
    select 1
    from public.class_staff_assignments csa
    join public.contact_book_profiles p on p.id = csa.profile_id
    where csa.class_id = target_class_id
      and csa.profile_id = auth.uid()
      and csa.role = 'homeroom_teacher'
      and csa.starts_on <= current_date
      and (csa.ends_on is null or csa.ends_on >= current_date)
      and p.approval_status = 'approved'
      and p.is_active
  );
$$;

create or replace function public.can_manage_subject(target_class_subject_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.class_subjects cs
    where cs.id = target_class_subject_id
      and public.can_manage_class(cs.class_id)
  ) or exists (
    select 1
    from public.class_staff_assignments csa
    join public.contact_book_profiles p on p.id = csa.profile_id
    where csa.class_subject_id = target_class_subject_id
      and csa.profile_id = auth.uid()
      and csa.role = 'subject_teacher'
      and csa.starts_on <= current_date
      and (csa.ends_on is null or csa.ends_on >= current_date)
      and p.approval_status = 'approved'
      and p.is_active
  );
$$;

create or replace function public.is_subject_helper(target_class_subject_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.student_helper_assignments sha
    join public.students s on s.id = sha.student_id
    join public.contact_book_profiles p on p.id = s.profile_id
    where sha.class_subject_id = target_class_subject_id
      and s.profile_id = auth.uid()
      and sha.starts_on <= current_date
      and (sha.ends_on is null or sha.ends_on >= current_date)
      and s.is_active
      and p.approval_status = 'approved'
      and p.is_active
  );
$$;

create or replace function public.can_publish_subject(target_class_subject_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.can_manage_subject(target_class_subject_id)
      or public.is_subject_helper(target_class_subject_id);
$$;

create or replace function public.can_view_class(target_class_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.can_manage_class(target_class_id) or exists (
    select 1
    from public.class_staff_assignments csa
    join public.contact_book_profiles p on p.id = csa.profile_id
    where csa.class_id = target_class_id
      and csa.profile_id = auth.uid()
      and csa.starts_on <= current_date
      and (csa.ends_on is null or csa.ends_on >= current_date)
      and p.approval_status = 'approved'
      and p.is_active
  ) or exists (
    select 1
    from public.students s
    join public.contact_book_profiles p on p.id = s.profile_id
    where s.class_id = target_class_id
      and s.profile_id = auth.uid()
      and s.is_active
      and p.approval_status = 'approved'
      and p.is_active
  );
$$;

create or replace function public.can_view_class_roster(target_class_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.can_manage_class(target_class_id) or exists (
    select 1
    from public.class_staff_assignments csa
    join public.contact_book_profiles p on p.id = csa.profile_id
    where csa.class_id = target_class_id
      and csa.profile_id = auth.uid()
      and csa.starts_on <= current_date
      and (csa.ends_on is null or csa.ends_on >= current_date)
      and p.approval_status = 'approved'
      and p.is_active
  ) or exists (
    select 1
    from public.student_helper_assignments sha
    join public.students s on s.id = sha.student_id
    join public.class_subjects cs on cs.id = sha.class_subject_id
    join public.contact_book_profiles p on p.id = s.profile_id
    where s.profile_id = auth.uid()
      and cs.class_id = target_class_id
      and sha.starts_on <= current_date
      and (sha.ends_on is null or sha.ends_on >= current_date)
      and p.approval_status = 'approved'
      and p.is_active
  );
$$;

alter table public.schools enable row level security;
alter table public.academic_years enable row level security;
alter table public.academic_terms enable row level security;
alter table public.classes enable row level security;
alter table public.contact_book_profiles enable row level security;
alter table public.students enable row level security;
alter table public.student_activation_codes enable row level security;
alter table public.auth_rate_limits enable row level security;
alter table public.subjects enable row level security;
alter table public.class_subjects enable row level security;
alter table public.class_staff_assignments enable row level security;
alter table public.student_helper_assignments enable row level security;
alter table public.student_subject_groups enable row level security;
alter table public.assignments enable row level security;
alter table public.assignment_recipients enable row level security;
alter table public.submission_checks enable row level security;
alter table public.submission_exceptions enable row level security;
alter table public.submission_status_events enable row level security;
alter table public.announcements enable row level security;
alter table public.announcement_reads enable row level security;
alter table public.honor_entries enable row level security;
alter table public.assessment_periods enable row level security;
alter table public.assessments enable row level security;
alter table public.student_scores enable row level security;

create policy contact_book_profiles_read_self on public.contact_book_profiles
for select to authenticated using (id = auth.uid() or public.contact_book_is_admin());

create policy contact_book_profiles_admin_update on public.contact_book_profiles
for update to authenticated
using (public.contact_book_is_admin())
with check (public.contact_book_is_admin());

create policy students_read_allowed on public.students
for select to authenticated using (
  public.is_student_self(id)
  or public.can_view_class_roster(class_id)
);

create policy students_admin_all on public.students
for all to authenticated
using (public.can_manage_class(class_id))
with check (public.can_manage_class(class_id));

create policy activation_codes_admin_all on public.student_activation_codes
for all to authenticated
using (
  exists (
    select 1 from public.students s
    where s.id = student_id and public.can_manage_class(s.class_id)
  )
)
with check (
  exists (
    select 1 from public.students s
    where s.id = student_id and public.can_manage_class(s.class_id)
  )
);

create policy staff_read_self_or_admin on public.class_staff_assignments
for select to authenticated using (
  profile_id = auth.uid() or public.can_manage_class(class_id)
);

create policy staff_admin_all on public.class_staff_assignments
for all to authenticated
using (public.can_manage_class(class_id))
with check (public.can_manage_class(class_id));

create policy helper_read_self_or_staff on public.student_helper_assignments
for select to authenticated using (
  public.is_student_self(student_id)
  or public.can_manage_subject(class_subject_id)
);

create policy helper_staff_all on public.student_helper_assignments
for all to authenticated
using (public.can_manage_subject(class_subject_id))
with check (public.can_manage_subject(class_subject_id));

create policy groups_read_allowed on public.student_subject_groups
for select to authenticated using (
  public.is_student_self(student_id)
  or public.can_manage_subject(class_subject_id)
);

create policy groups_staff_all on public.student_subject_groups
for all to authenticated
using (public.can_manage_subject(class_subject_id))
with check (public.can_manage_subject(class_subject_id));

create policy assignments_read_allowed on public.assignments
for select to authenticated using (
  public.can_publish_subject(class_subject_id)
  or (is_active and exists (
    select 1 from public.assignment_recipients ar
    where ar.assignment_id = assignments.id
      and ar.student_id = public.current_student_id()
  ))
);

create policy assignments_publish on public.assignments
for insert to authenticated with check (
  public.can_publish_subject(class_subject_id)
  and published_by = auth.uid()
);

create policy assignments_update_staff_or_owner_helper on public.assignments
for update to authenticated using (
  public.can_manage_subject(class_subject_id)
  or (public.is_subject_helper(class_subject_id) and published_by = auth.uid())
)
with check (
  public.can_manage_subject(class_subject_id)
  or (public.is_subject_helper(class_subject_id) and published_by = auth.uid())
);

create policy recipients_read_allowed on public.assignment_recipients
for select to authenticated using (
  public.is_student_self(student_id)
  or exists (
    select 1 from public.assignments a
    where a.id = assignment_id and public.can_publish_subject(a.class_subject_id)
  )
);

create policy submission_checks_read_allowed on public.submission_checks
for select to authenticated using (
  exists (
    select 1 from public.assignments a
    where a.id = assignment_id and public.can_publish_subject(a.class_subject_id)
  )
);

create policy submission_checks_insert_allowed on public.submission_checks
for insert to authenticated with check (
  checked_by = auth.uid()
  and exists (
    select 1 from public.assignments a
    where a.id = assignment_id and public.can_publish_subject(a.class_subject_id)
  )
);

create policy exceptions_read_allowed on public.submission_exceptions
for select to authenticated using (
  public.is_student_self(student_id)
  or exists (
    select 1 from public.assignments a
    where a.id = assignment_id and public.can_publish_subject(a.class_subject_id)
  )
);

create policy exceptions_insert_allowed on public.submission_exceptions
for insert to authenticated with check (
  first_recorded_by = auth.uid()
  and last_updated_by = auth.uid()
  and exists (
    select 1 from public.assignments a
    where a.id = assignment_id and public.can_publish_subject(a.class_subject_id)
  )
);

create policy exceptions_teacher_update on public.submission_exceptions
for update to authenticated using (
  exists (
    select 1 from public.assignments a
    where a.id = assignment_id and public.can_manage_subject(a.class_subject_id)
  )
)
with check (
  last_updated_by = auth.uid()
  and exists (
    select 1 from public.assignments a
    where a.id = assignment_id and public.can_manage_subject(a.class_subject_id)
  )
);

create policy exception_events_read_allowed on public.submission_status_events
for select to authenticated using (
  exists (
    select 1
    from public.submission_exceptions se
    join public.assignments a on a.id = se.assignment_id
    where se.id = submission_exception_id
      and (
        public.is_student_self(se.student_id)
        or public.can_publish_subject(a.class_subject_id)
      )
  )
);

create policy announcements_read_class on public.announcements
for select to authenticated using (
  (is_active and public.can_view_class(class_id))
  or public.can_manage_class(class_id)
);

create policy announcements_admin_all on public.announcements
for all to authenticated
using (public.can_manage_class(class_id))
with check (public.can_manage_class(class_id) and published_by = auth.uid());

create policy announcement_reads_read_allowed on public.announcement_reads
for select to authenticated using (
  public.is_student_self(student_id)
  or exists (
    select 1 from public.announcements a
    where a.id = announcement_id and public.can_manage_class(a.class_id)
  )
);

create policy announcement_reads_student_insert on public.announcement_reads
for insert to authenticated with check (public.is_student_self(student_id));

create policy honor_read_class on public.honor_entries
for select to authenticated using (
  (is_visible and public.can_view_class(class_id))
  or public.can_manage_class(class_id)
);

create policy honor_admin_all on public.honor_entries
for all to authenticated
using (public.can_manage_class(class_id))
with check (public.can_manage_class(class_id) and created_by = auth.uid());

create policy scores_read_allowed on public.student_scores
for select to authenticated using (
  public.is_student_self(student_id)
  or exists (
    select 1
    from public.assessments a
    where a.id = assessment_id
      and public.can_manage_subject(a.class_subject_id)
  )
);

-- 參照資料採已核准使用者唯讀；建立與修改將由導師管理流程處理。
create policy schools_read_approved on public.schools
for select to authenticated using (public.is_approved_user());

create policy academic_years_read_approved on public.academic_years
for select to authenticated using (public.is_approved_user());

create policy academic_terms_read_approved on public.academic_terms
for select to authenticated using (public.is_approved_user());

create policy classes_read_allowed on public.classes
for select to authenticated using (public.can_view_class(id));

create policy subjects_read_approved on public.subjects
for select to authenticated using (public.is_approved_user());

create policy class_subjects_read_class on public.class_subjects
for select to authenticated using (public.can_view_class(class_id));

create policy subjects_admin_all on public.subjects
for all to authenticated
using (public.contact_book_is_admin())
with check (public.contact_book_is_admin());

create policy class_subjects_admin_all on public.class_subjects
for all to authenticated
using (public.can_manage_class(class_id))
with check (public.can_manage_class(class_id));

commit;

