-- 英文單字多例句資料庫。
-- A 組可使用所有適合 A 組的例句進行句子重組與句子口說；
-- B 組只在少量口說題使用標示為適合 B 組的簡短例句。

create table if not exists public.vocabulary_examples (
  id bigint generated by default as identity primary key,
  vocabulary_id bigint not null references public.vocabulary(id) on delete cascade,
  sentence text not null,
  sentence_translation text not null,
  suitable_for_a boolean not null default true,
  suitable_for_b boolean not null default false,
  display_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vocabulary_examples_sentence_unique unique (vocabulary_id, sentence),
  constraint vocabulary_examples_sentence_not_blank check (length(trim(sentence)) > 0),
  constraint vocabulary_examples_translation_not_blank check (length(trim(sentence_translation)) > 0)
);

create index if not exists vocabulary_examples_vocabulary_idx
  on public.vocabulary_examples(vocabulary_id, is_active, display_order);

drop trigger if exists set_vocabulary_examples_updated_at on public.vocabulary_examples;
create trigger set_vocabulary_examples_updated_at
before update on public.vocabulary_examples
for each row execute function public.set_updated_at();

alter table public.vocabulary_examples enable row level security;

drop policy if exists vocabulary_examples_select_authenticated on public.vocabulary_examples;
create policy vocabulary_examples_select_authenticated
on public.vocabulary_examples for select
to authenticated
using (is_active or public.is_admin());

drop policy if exists vocabulary_examples_admin_insert on public.vocabulary_examples;
create policy vocabulary_examples_admin_insert
on public.vocabulary_examples for insert
to authenticated
with check (public.is_admin());

drop policy if exists vocabulary_examples_admin_update on public.vocabulary_examples;
create policy vocabulary_examples_admin_update
on public.vocabulary_examples for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists vocabulary_examples_admin_delete on public.vocabulary_examples;
create policy vocabulary_examples_admin_delete
on public.vocabulary_examples for delete
to authenticated
using (public.is_admin());

grant select, insert, update, delete on public.vocabulary_examples to authenticated;
grant usage, select on sequence public.vocabulary_examples_id_seq to authenticated;

-- 修正三筆原有例句的文法或用字，再納入主要例句。
update public.vocabulary
set sentence = 'Shu-Yao usually gets up at 6:20 a.m. on weekdays to catch the school bus.',
    sentence_translation = '書瑤平日通常早上 6:20 起床搭校車。'
where word = 'weekday' and translation = '平日';

update public.vocabulary
set sentence = 'Yu-Xuan really likes to borrow books from the SLJH library.',
    sentence_translation = '雨璇真的很喜歡從石榴國中的圖書館借書。'
where word = 'library' and translation = '圖書館';

update public.vocabulary
set sentence = 'Zi-Jie and Cheng-Ze are going to the movie theater this weekend to see the new Marvel movie.',
    sentence_translation = '字杰和承澤這週末要去電影院看最新的漫威電影。'
where word = 'movie theater' and translation = '電影院';

-- 先保留每一筆單字原有的教師例句，確保所有課別都有可用例句。
insert into public.vocabulary_examples (
  vocabulary_id,
  sentence,
  sentence_translation,
  suitable_for_a,
  suitable_for_b,
  display_order
)
select
  vocabulary.id,
  vocabulary.sentence,
  vocabulary.sentence_translation,
  true,
  false,
  10
from public.vocabulary
where length(trim(vocabulary.sentence)) > 0
  and length(trim(vocabulary.sentence_translation)) > 0
on conflict (vocabulary_id, sentence) do update set
  sentence_translation = excluded.sentence_translation,
  suitable_for_a = true,
  display_order = least(public.vocabulary_examples.display_order, excluded.display_order),
  is_active = true,
  updated_at = now();

-- 第二冊第六課的簡短替代例句：A 組可隨機重組，B 組可用於少量句子口說。
with curated_examples(word, translation, sentence, sentence_translation) as (
  values
    ('sure', '確定的', 'I am sure this is the right bus.', '我確定這是正確的公車。'),
    ('dangerous', '危險的', 'It is dangerous to play on the road.', '在馬路上玩耍很危險。'),
    ('stand in ... way', '阻礙…… / 擋到……的路', 'Do not let fear stand in your way.', '不要讓恐懼阻礙你。'),
    ('nothing', '沒有東西、沒事', 'There is nothing under the desk.', '桌子下面什麼都沒有。'),
    ('weekday', '平日', 'I get up early on every weekday.', '我每個平日都很早起床。'),
    ('wait', '等一下、等待', 'Please wait for me at the gate.', '請在門口等我。'),
    ('map', '地圖', 'This map shows the way to the station.', '這張地圖標示了前往車站的路。'),
    ('fair', '園遊會；展覽', 'Our school has a book fair today.', '我們學校今天有書展。'),
    ('will', '決心', 'She has the will to keep trying.', '她有繼續努力的決心。'),
    ('clear', '晴朗的', 'The sky is clear this morning.', '今天早上的天空很晴朗。'),
    ('sky', '天空', 'Birds are flying in the blue sky.', '鳥兒正在藍天中飛翔。'),
    ('idea', '想法；主意', 'I have an idea for our class poster.', '我對班級海報有一個想法。'),
    ('corner', '街角', 'Turn right at the next corner.', '在下一個街角右轉。'),
    ('road', '路', 'Be careful when you cross the road.', '過馬路時要小心。'),
    ('cross', '跨越', 'We cross the street after the light turns green.', '綠燈亮後我們才過馬路。'),
    ('block', '街區', 'Walk one block and turn left.', '走一個街區後左轉。'),
    ('station', '車站', 'My father is waiting at the train station.', '我爸爸正在火車站等候。'),
    ('bank', '銀行', 'The bank is across from the library.', '銀行在圖書館對面。'),
    ('library', '圖書館', 'We read books in the school library.', '我們在學校圖書館看書。'),
    ('hospital', '醫院', 'The sick boy went to the hospital.', '那位生病的男孩去了醫院。'),
    ('movie theater', '電影院', 'The movie theater is next to the bank.', '電影院在銀行旁邊。'),
    ('ride', '騎；乘坐', 'I ride my bike to school every day.', '我每天騎腳踏車上學。'),
    ('across from', '在……對面', 'The bakery is across from the station.', '麵包店在車站對面。'),
    ('along', '沿著', 'We walked along the river after lunch.', '午餐後我們沿著河邊散步。'),
    ('bakery', '麵包店', 'This bakery sells fresh bread.', '這家麵包店販售新鮮麵包。'),
    ('foot', '腳', 'We go to school on foot.', '我們走路上學。'),
    ('metro', '地鐵；捷運', 'We take the metro to the zoo.', '我們搭捷運去動物園。'),
    ('boat', '船', 'They crossed the river by boat.', '他們搭船渡河。'),
    ('horse', '馬', 'The girl can ride a horse.', '那位女孩會騎馬。'),
    ('sleigh', '雪橇', 'Santa rides a sleigh on Christmas Eve.', '聖誕老人會在聖誕夜乘坐雪橇。'),
    ('straight', '直地', 'Go straight and turn left at the bank.', '直走並在銀行左轉。'),
    ('left', '左邊', 'The library is on your left.', '圖書館在你的左邊。'),
    ('right', '右邊', 'The station is on your right.', '車站在你的右邊。'),
    ('may', '也許', 'It may rain this afternoon.', '今天下午也許會下雨。'),
    ('woman', '女人', 'The woman is our new English teacher.', '那位女士是我們的新英文老師。'),
    ('minute', '分鐘', 'Please give me one minute.', '請給我一分鐘。'),
    ('mate', '夥伴', 'Kevin is my best mate at school.', 'Kevin 是我在學校最好的夥伴。'),
    ('turn', '轉向、轉彎', 'Turn left at the next corner.', '在下一個街角左轉。'),
    ('train', '火車', 'We take the train to Taipei.', '我們搭火車去臺北。'),
    ('hike', '長途步行、健行、爬山', 'We plan to hike this Sunday.', '我們計畫這個星期日去健行。'),
    ('lost', '迷路的', 'I am lost. Can you help me?', '我迷路了。你可以幫我嗎？'),
    ('wrong', '錯誤的、不對的', 'This is the wrong answer.', '這是錯誤的答案。'),
    ('in back of', '在……後面', 'The bike is in back of the house.', '腳踏車在房子後面。')
)
insert into public.vocabulary_examples (
  vocabulary_id,
  sentence,
  sentence_translation,
  suitable_for_a,
  suitable_for_b,
  display_order
)
select
  vocabulary.id,
  curated_examples.sentence,
  curated_examples.sentence_translation,
  true,
  true,
  20
from curated_examples
join public.vocabulary
  on vocabulary.word = curated_examples.word
 and vocabulary.translation = curated_examples.translation
on conflict (vocabulary_id, sentence) do update set
  sentence_translation = excluded.sentence_translation,
  suitable_for_a = true,
  suitable_for_b = true,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

